sudo: false
language: android
android:
  components:
    - build-tools-24.0.1
    - android-24
    - extra-android-support
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository

script: ./gradlew clean check assembleDebug
