language: android
android:
  components:
    - build-tools-23.0.1
    - android-23
    - extra-android-support
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository

script: ./gradlew clean check assembleDebug
